#!/bin/sh
set -e
set -x

# configure tomcat admin user/password
TOMCAT_HOME=/usr/local/tomcat
TOMCAT_ADMIN_USER=${TOMCAT_ADMIN_USER:-admin}
TOMCAT_ADMIN_PASSWORD=${TOMCAT_ADMIN_PASSWORD:-admin}
sed 's,{{TOMCAT_ADMIN_USER}},'"${TOMCAT_ADMIN_USER}"',g' -i ${TOMCAT_HOME}/conf/tomcat-users.xml
sed 's,{{TOMCAT_ADMIN_PASSWORD}},'"${TOMCAT_ADMIN_PASSWORD}"',g' -i ${TOMCAT_HOME}/conf/tomcat-users.xml

# postgresql db
DB_TYPE=${DB_TYPE:-}
DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-}
DB_NAME=${DB_NAME:-}
DB_USER=${DB_USER:-}
DB_PASS=${DB_PASS:-}


sed 's/{{DB_PORT}}/'"${DB_PORT}"'/g' -i /assets/config/db.properties
sed 's/{{DB_HOST}}/'"${DB_HOST}"'/g' -i /assets/config/db.properties
sed 's/{{DB_NAME}}/'"${DB_NAME}"'/g' -i /assets/config/db.properties
sed 's/{{DB_USER}}/'"${DB_USER}"'/g' -i /assets/config/db.properties
sed 's/{{DB_PASS}}/'"${DB_PASS}"'/g' -i /assets/config/db.properties

sed 's/{{DB_PORT}}/'"${DB_PORT}"'/g' -i /assets/config/activiti-app.properties
sed 's/{{DB_HOST}}/'"${DB_HOST}"'/g' -i /assets/config/activiti-app.properties
sed 's/{{DB_NAME}}/'"${DB_NAME}"'/g' -i /assets/config/activiti-app.properties
sed 's/{{DB_USER}}/'"${DB_USER}"'/g' -i /assets/config/activiti-app.properties
sed 's/{{DB_PASS}}/'"${DB_PASS}"'/g' -i /assets/config/activiti-app.properties


cp -f /assets/config/activiti-app.properties ${TOMCAT_HOME}/webapps/activiti-app/WEB-INF/classes/META-INF/activiti-app/
cp -f /assets/config/db.properties ${TOMCAT_HOME}/webapps/activiti-rest/WEB-INF/classes/

${TOMCAT_HOME}/bin/catalina.sh run
